CLASS zcds2_currency_conversion1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcds2_currency_conversion1 IMPLEMENTATION.
ENDCLASS.
